#!/bin/bash
set -e

mkdir -p "$HOME/Music"

yt-dlp -f "ba[ext=m4a]/ba/b" \
  --extract-audio \
  --audio-format m4a \
  --cookies "$HOME/.config/yt-dlp/cookies.txt" \
  --embed-metadata \
  --add-metadata \
  --embed-thumbnail \
  --ppa "ffmpeg: -disposition:v:0 default -vf crop='ih:ih'" \
  --output "$HOME/Music/%(artist,uploader)s - %(title)s.%(ext)s" "$@"
